<?php

namespace App\Support;

/**
 * Règles de validation par section pour le centre de paramètres (DTO métier).
 */
class SettingsCenterRules
{
    /** @return array<string, mixed> */
    public static function rules(string $section): array
    {
        $s = 'nullable|string|max:65535';
        $email = 'nullable|email|max:255';
        // Array form: `nullable|string|regex:...` as one string splits on every `|`, breaking the regex.
        $urlEmptyOrHttp = ['nullable', 'string', 'max:2048', 'regex:/^(?:$|https?:\/\/.+)$/i'];

        return match ($section) {
            'general' => [
                'company' => 'required|array',
                'company.name' => 'required|string|max:255',
                'company.logoUrl' => ['nullable', 'string', 'max:2048'],
                'company.phone' => 'nullable|string|max:40',
                'company.email' => $email,
                'company.address' => $s,
                'company.city' => 'nullable|string|max:120',
                'company.website' => $urlEmptyOrHttp,
                'company.ice' => 'nullable|string|max:80',
                'company.ifNumber' => 'nullable|string|max:80',
                'company.rc' => 'nullable|string|max:80',
                'system' => 'nullable|array',
                'system.timezone' => 'nullable|string|max:80',
                'system.defaultLanguage' => 'nullable|string|max:16',
                'system.currency' => 'nullable|string|max:16',
                'system.dateFormat' => 'nullable|string|max:40',
                'branding' => 'nullable|array',
                'branding.primaryColor' => 'nullable|string|max:32',
                'branding.crmDisplayName' => 'nullable|string|max:255',
                'workflow' => 'nullable|array',
                'workflow.defaultLeadStatus' => $s,
                'workflow.defaultOrderStatus' => $s,
                'workflow.leadSlaHours' => 'nullable|numeric|min:0|max:8760',
                'navigation' => 'nullable|array',
                'navigation.items' => 'nullable|array',
                'navigation.items.*' => 'boolean',
                'products' => 'nullable|array',
                'products.categories' => 'nullable|array',
                'products.categories.*' => 'string|max:255',
                'products.types' => 'nullable|array',
                'products.types.*' => 'string|max:255',
                'suppliers' => 'nullable|array',
                'suppliers.categories' => 'nullable|array',
                'suppliers.categories.*' => 'string|max:255',
            ],
            'integrations' => [
                'email' => 'nullable|array',
                'email.smtpHost' => 'nullable|string|max:255',
                'email.smtpPort' => 'nullable|integer|min:1|max:65535',
                'email.smtpUser' => 'nullable|string|max:255',
                'email.smtpPassword' => 'nullable|string|max:2048',
                'email.smtpEncryption' => 'nullable|string|max:32',
                'email.senderName' => 'nullable|string|max:255',
                'sms' => 'nullable|array',
                'sms.provider' => $s,
                'sms.apiKey' => 'nullable|string|max:2048',
                'sms.sender' => 'nullable|string|max:64',
                'storage' => 'nullable|array',
                'storage.provider' => 'nullable|string|max:64',
                'storage.bucket' => 'nullable|string|max:255',
                'storage.accessKey' => 'nullable|string|max:512',
                'storage.secretKey' => 'nullable|string|max:512',
                'webhooks' => 'nullable|array',
                'webhooks.url' => $urlEmptyOrHttp,
                'webhooks.secret' => 'nullable|string|max:2048',
            ],
            'delivery' => [
                'defaults' => 'nullable|array',
                'defaults.defaultCarrierId' => $s,
                'defaults.defaultShippingFee' => 'nullable|numeric|min:0',
                'defaults.averageDeliveryDays' => 'nullable|numeric|min:0',
                'rules' => 'nullable|array',
                'rules.insuranceEnabled' => 'nullable|boolean',
                'rules.allowOpenPackage' => 'nullable|boolean',
                'rules.autoTrackingNumber' => 'nullable|boolean',
                'rules.autoSyncTracking' => 'nullable|boolean',
                'carriers' => 'nullable|array',
                'carriers.sendit' => 'nullable|array',
                'carriers.sendit.apiUrl' => $urlEmptyOrHttp,
                'carriers.sendit.publicKey' => 'nullable|string|max:2048',
                'carriers.sendit.secretKey' => 'nullable|string|max:2048',
                'carriers.ameex' => 'nullable|array',
                'carriers.ameex.apiUrl' => $urlEmptyOrHttp,
                'carriers.ameex.apiKey' => 'nullable|string|max:2048',
                'cod' => 'nullable|array',
                'cod.reconciliationDelayDays' => 'nullable|numeric|min:0',
                'cod.disputeTolerance' => 'nullable|numeric|min:0',
            ],
            'whatsapp' => [
                'connection' => 'nullable|array',
                'connection.provider' => 'nullable|string|max:120',
                'connection.apiBaseUrl' => $urlEmptyOrHttp,
                'connection.businessNumber' => 'nullable|string|max:40',
                'connection.apiToken' => 'nullable|string|max:4096',
                'connection.phoneId' => 'nullable|string|max:80',
                'connection.businessAccountId' => 'nullable|string|max:120',
                'connection.webhookVerifyToken' => 'nullable|string|max:2048',
                'connection.webhookUrlHint' => $urlEmptyOrHttp,
                'automation' => 'nullable|array',
                'automation.autoCreateLead' => 'nullable|boolean',
                'automation.autoAssignConversation' => 'nullable|boolean',
                'automation.autoReplies' => 'nullable|boolean',
                'automation.defaultWelcomeMessage' => $s,
                'templates' => 'nullable|array',
                'templates.orderConfirmation' => $s,
                'templates.delivery' => $s,
                'templates.followUp' => $s,
                'templates.upsell' => $s,
            ],
            'meta' => [
                'credentials' => 'nullable|array',
                'credentials.appId' => 'nullable|string|max:128',
                'credentials.appSecret' => 'nullable|string|max:2048',
                'credentials.accessToken' => 'nullable|string|max:4096',
                'credentials.businessId' => 'nullable|string|max:128',
                'ads' => 'nullable|array',
                'ads.attributionWindowDays' => 'nullable|numeric|min:0',
                'ads.syncFrequencyMinutes' => 'nullable|numeric|min:1',
                'ads.currency' => 'nullable|string|max:16',
                'targets' => 'nullable|array',
                'targets.cac' => 'nullable|numeric|min:0',
                'targets.cpa' => 'nullable|numeric|min:0',
                'targets.roas' => 'nullable|numeric|min:0',
            ],
            'finance' => [
                'global' => 'nullable|array',
                'global.taxPercent' => 'nullable|numeric|min:0|max:100',
                'global.invoicePrefix' => 'nullable|string|max:32',
                'global.invoiceAutoNumbering' => 'nullable|boolean',
                'cod' => 'nullable|array',
                'cod.delayDays' => 'nullable|numeric|min:0',
                'charges' => 'nullable|array',
                'charges.categories' => $s,
                'charges.expenseValidation' => $s,
                'accounting' => 'nullable|array',
                'accounting.enableExport' => 'nullable|boolean',
                'accounting.exportFormat' => 'nullable|string|max:64',
            ],
            'security' => [
                'auth' => 'nullable|array',
                'auth.enable2fa' => 'nullable|boolean',
                'auth.sessionTimeoutMinutes' => 'nullable|integer|min:5|max:525600',
                'auth.maxLoginAttempts' => 'nullable|integer|min:1|max:100',
                'passwords' => 'nullable|array',
                'passwords.minLength' => 'nullable|integer|min:4|max:128',
                'passwords.requireComplexity' => 'nullable|boolean',
                'network' => 'nullable|array',
                'network.ipWhitelist' => $s,
                'network.allowedOrigins' => $s,
                'data' => 'nullable|array',
                'data.encryptSensitiveFields' => 'nullable|boolean',
                'data.auditRetentionDays' => 'nullable|integer|min:1|max:3650',
            ],
            default => [],
        };
    }
}
